from app.schemas.user import (
    ErrorResponse,
    TokenResponse,
    UserLoginRequest,
    UserRegisterRequest,
    UserResponse,
    ValidationErrorDetail,
    ValidationErrorResponse,
)
from app.schemas.lms import (
    AnswerResponse,
    AssignmentCreate,
    AssignmentResponse,
    CourseCreate,
    CourseResponse,
    DoubtCreate,
    DoubtResponse,
    EnrolledStudent,
    GradeSubmission,
    MaterialResponse,
    SubmissionResponse,
)

__all__ = [
    "UserRegisterRequest",
    "UserLoginRequest",
    "UserResponse",
    "TokenResponse",
    "ErrorResponse",
    "ValidationErrorDetail",
    "ValidationErrorResponse",
    "CourseCreate",
    "CourseResponse",
    "AssignmentCreate",
    "AssignmentResponse",
    "SubmissionResponse",
    "GradeSubmission",
    "MaterialResponse",
    "EnrolledStudent",
    "DoubtCreate",
    "DoubtResponse",
    "AnswerResponse",
]
